apiVersion: v1
kind: Service
metadata:
  labels:
    service: snipeit
  name: snipeit
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    service: snipeit
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: snipeit-mysql
  name: snipeit-mysql
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    service: snipeit-mysql