apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: radarr
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: radarr
  targetCPUUtilizationPercentage: 50