apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpservermon
  name: phpservermon
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: phpservermon
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpservermon-db
  name: phpservermon-db
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    app: phpservermon-db