apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flexget-config
spec:
  storageClassName: "default"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flexget-data
spec:
  storageClassName: "default"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi