---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: smokeping-config
  labels:
    app: smokeping
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: smokeping-data
  labels:
    app: smokeping
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi


