apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tautulli
  namespace: default
spec:
  rules:
  - host: tautulli.lan
    http:
      paths:
      - backend:
          service:
            name: tautulli
            port:
              number: 8181
        path: /
        pathType: ImplementationSpecific