apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tautulli-conf
spec:
  storageClassName: "default"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tautulli-logs
spec:
  storageClassName: "default"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Mi