apiVersion: v1
kind: Service
metadata:
  labels:
    app: snipeit
  name: snipeit
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: snipeit
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: snipeit-db
  name: snipeit-db
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    app: snipeit-db