apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: organizr
  namespace: default
spec:
  rules:
  - host: organizr.lan
    http:
      paths:
      - backend:
          service:
            name: organizr
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific