apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wekan
  name: wekan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wekan
  template:
    metadata:
      labels:
        app: wekan
    spec:
      containers:
      - env:
        - name: BIGEVENTS_PATTERN
          value: NONE
        - name: BROWSER_POLICY_ENABLED
          value: "true"
        - name: CARD_OPENED_WEBHOOK_ENABLED
          value: "false"
        - name: MAIL_FROM
          value: Wekan Notifications <noreply.wekan@mydomain.com>
        - name: MAIL_URL
          value: smtp://smtp.sendgrid.net:25/?ignoreTLS=true&tls={rejectUnauthorized:false}
        - name: MONGO_URL
          value: mongodb://mongo:27017/wekan
        - name: RICHER_CARD_COMMENT_EDITOR
          value: "false"
        - name: ROOT_URL
          value: http://wekan.lan
        - name: SCROLLAMOUNT
          value: auto
        - name: SCROLLINERTIA
          value: "0"
        - name: WITH_API
          value: "true"
        image: wekanteam/wekan
        imagePullPolicy: Always
        name: wekan
        ports:
        - containerPort: 8080
      restartPolicy: Always