apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: varken-influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: varken-grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: varken
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
